vich_uploader:
    db_driver: orm

    mappings:
        pictures:
            uri_prefix: /medias/pictures
            upload_destination: '%kernel.project_dir%/public/medias/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer